apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: shitdetector-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend.shitdetector.svc.cluster.local:3000
            labels:
              namespace: shitdetector
              app: backend

      - job_name: tic-tac-arena-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend.tic-tac-arena.svc.cluster.local:3000
            labels:
              namespace: tic-tac-arena
              app: backend
