apiVersion: v1
kind: ConfigMap
metadata:
  name: tic-tac-arena-grafana-provisioning
  namespace: monitoring
data:
  tic-tac-arena-dashboards.yml: |
    apiVersion: 1
    providers:
      - name: Tic Tac Arena
        orgId: 1
        folder: Tic Tac Arena
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/tic-tac-arena-dashboards
